version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - "4200:4200"
    container_name: client_container
    depends_on:
      - webapi
      - api

  api:
    build:
      context: ./nodeapi
    restart: always
    ports:
      - "5000:5000"
    container_name: nodeapi_container
    depends_on:
      - emongo
      - nginx

  webapi:
    build:
      context: ./javaapi
    restart: always
    ports:
      - "9000:9000"
    container_name: javaapi_container
    depends_on:
      - emartdb

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    restart: always
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"

  emongo:
    restart: always
    image: mongo:4
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=epoc
    
  emartdb:
    image: mysql:8.0.33
    restart: always
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books