version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - "4200:4200"
    container_name: client_container
    restart: always
    depends_on:
      - api
      - webapi

  api:
    build:
      context: ./nodeapi
    ports:
      - "5000:5000"
    container_name: nodeapi_container
    restart: always
    depends_on:
      - emongo
      - nginx

  webapi:
    build:
      context: ./javaapi
    restart: always
    ports:
      - "9000:9000"
    container_name: javaapi_container
    depends_on:
      - emartdb

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    
  emongo:
    image: mongo:4
    ports:
      - "27017:27017"
    container_name: emongo_container

  emartdb:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    container_name: mysql_container